#ifndef SUBGRAPHMATCHING_CONFIG_H
#define SUBGRAPHMATCHING_CONFIG_H

#define MAXIMUM_QUERY_GRAPH_SIZE 64
#define PRINT_SEPARATOR "------------------------------"

#define OPTIMIZED_LABELED_GRAPH 0
#define ENABLE_FAILING_SET 1
#endif //SUBGRAPHMATCHING_CONFIG_H